var fs = require('fs');
var renderLicenseBadge = function (license) {
    return license === 'Apache' ? "[![License: Apache](https://letelds.io/badge/License-Apache%202.0-lightgreen.svg)](https://opensource.org/licenses/Apache-2.0)"
        : license === 'MIT' ? "[![License: MIT](https://img.shields.io/badge/License-MIT-hotpink.svg)](https://opensource.org/licenses/MIT)"
            : license === 'Modzilla' ? "[![License: MPL 2.0](https://img.shields.io/badge/License-MPL%202.0-orange.svg)](https://opensource.org/licenses/MPL-2.0)"
                : 'None Provided';
};
module.exports = renderMarkUp = function (response) {
    var markUp = "# __" + response.projectTitle + "__\n## __Description__\n" + response.description + "\n## __Table of Contents__\n* [Dependencies](#dependencies)\n* [Installation](#installation)\n* [Usage](#usage)\n* [Tests](#tests)\n* [License](#license)\n* [Badges](#badges)\n* [ScreenShot](#screenshot)\n* [Contributors](#contributors)\n* [Contact Information](#questions)\n* [Demo](#demo)\n## __Dependencies__\n" + response.dependencies + "\n## __Tests__\n" + response.tests + "\n## __Installation__\n  " + response.installation + "\n## __Usage__\n" + response.usage + "\n## __License__\n__Copyright " + response.copyright_year + " " + response.copyright_holder + "__\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n## __Badges__\n" + renderLicenseBadge(response.license) + "\n## __ScreenShot__\n![Screenshot of Application](" + response.image + ")\n## __Contributors__\n" + response.contributors + "\n## __Questions__\nIf you would like to contribute to the project please contact me below: \n* [GitHub](https://github.com/" + response.github + ")\n* [E-mail](mailto:" + response.email + ")\n## __Demo__\n![Application Demo](link to image / GIF)";
    fs.writeFile('../README.md', markUp, function (err) {
        err ? console.error(err) : console.log('File Written!');
    });
};
